### ISSUE TITLE
New set up.

### ISSUE THREAD

**Issue by andrewm659** [PureStorage-OpenConnect/pure-fb-openmetrics-exporter#12]
I am trying to set this up on RHEL 7 using docker.  I was able to get the docker images deployed but I have multiple endpoints to monitor with different API tokens.  I want to set up a files_sd config to be able to add and remove endpoints.   The top portion is with the previous pure_exporter, the bottom is the new way.

`---`
`#- targets:`
`#        - INT_IP_ADDR`
`#          labels:`
`#                env: prod`
`#                authorization:`
`#                credentials: SOME_API_KEY`
`#        - INT_IP_ADDR`
`#          labels:`
`#                env: prod`
`#                authorization:`
`#                credentials: SOME_API_KEY`

`params:`
`      endpoint: INT_IP_ADDR`
`      authorization:`
`              credentials: SOME_API_KEY`
`      endpoint: INT_IP_ADDR`
`      authorization:`
`              credentials: SOME_API_KEY`

**Comment by james-laing** [comment]
@andrewm659 this looks like you are trying to get data into Prometheus.

If so, each endpoint needs to be declared in it's entirety including the authorisation token.

[Here](https://github.com/PureStorage-OpenConnect/pure-fb-openmetrics-exporter/blob/main/extra/prometheus/prometheus.yaml) is an example of a prometheus.yaml file.

Let us know if you are still requiring help with this.

**Comment by genegr** [comment]
In the new release that will go live the next week there is also the possibility to use a tokens map file, that helps simplifying the configuration on the Prometheus config file. Please check the README file once the new minor release is out.
