### ISSUE TITLE
readonly user on FB

### ISSUE THREAD

**Issue by ToMo999** [PureStorage-OpenConnect/pure-fb-openmetrics-exporter#17]
Hi,
you write in the [guide](https://github.com/PureStorage-OpenConnect/pure-fb-openmetrics-exporter/blob/main/extra/grafana/README.md#setup) that it is possible to create a new readonly user. I am sure this is not possible. On Flashblades there is only the local pureuser. 
You can only add a LDAP-user for monitoring, add it to a ad-group and map this group to readonly.  Or is there any method?

Regards

**Comment by james-laing** [comment]
@ToMo999 you are absolutely correct in your assessment. I have an update ready to push with a bunch of updates shortly. Thanks for raising this.
