### ISSUE TITLE
Feature Request for Volume Exports Metrics

### ISSUE THREAD

**Issue by jmg011** [PureStorage-OpenConnect/pure-fb-openmetrics-exporter#19]
**Enhancement Request:** Feature Request for Volume Exports Metrics

**Comment by sdodsley** [comment]
@jmg011 could you expand on this? I'm not sure what you are referring to.

**Comment by jmg011** [comment]
@sdodsley - I meant to request the metrics for export policy on the volumes in Pure Blade Exporter.

**Comment by genegr** [comment]
I am assuming you mean an info-style metric that shows the NFS export rules. Would something like this work for you?

purefb_nfs_export_rule{policy="mypolicy01",client="10.0.0.2",permission="ro",security="krb5i, krb5p",access="no-squash",anon_uid="1000",anon_gid="1001",secure="false",fileid-32bit="true",atime="true",index="3"} 1

That is certainly feasible.

**Comment by jmg011** [comment]
Hi @genegr - Correct. Something like this where I have policy name and other labels you have mentioned. For the given client though, that can be in different data-point. For example, note client label with different clients for the given policy and other associated labels like index.

purefb_nfs_export_rule{policy="mypolicy01",client="**client-1**",permission="ro",security="krb5i, krb5p",access="no-squash",anon_uid="1000",anon_gid="1001",secure="false",fileid-32bit="true",atime="true",index="**3**"} 1

purefb_nfs_export_rule{policy="mypolicy01",client="**client-2**",permission="ro",security="krb5i, krb5p",access="no-squash",anon_uid="1000",anon_gid="1001",secure="false",fileid-32bit="true",atime="true",index="**4**"} 1

purefb_nfs_export_rule{policy="mypolicy01",client="**client-3**",permission="ro",security="krb5i, krb5p",access="no-squash",anon_uid="1000",anon_gid="1001",secure="false",fileid-32bit="true",atime="true",index="**5**"} 1

**Comment by jmg011** [comment]
@genegr - We will also need another metric called purefb_volume_export_policy. In this metric, we will have just the volume and policy name. 

This way I can have policy metric with all the client rules and volume policy metric that I can join to get additional details.

Let me know if it is something that can be provided as a nightly build and possible ETA for this feature.

**Comment by genegr** [comment]
Both metrics can be exported. Will try to work at that the next days and hopefully have it done by the end of the week.

**Comment by jmg011** [comment]
@genegr - Perfect. Thank you so much!!

**Comment by jmg011** [comment]
Hi @genegr - Any update on this feature?

**Comment by jmg011** [comment]
Hi @genegr - Any update on this feature request?

**Comment by jmg011** [comment]
Hi @sdodsley - Can you help get the status update on this request?

**Comment by jmg011** [comment]
Hi @sdodsley - Any update on this?

**Comment by sdodsley** [comment]
@jmg011 this work is apparently done. Just a few other things to complete for other customer requests

**Comment by jmg011** [comment]
@sdodsley - Thanks for the update. Any ETA on the release?

**Comment by sdodsley** [comment]
We expect to cut a new release next week

**Comment by jmg011** [comment]
@sdodsley - Thank you. Please let me know when the new version is released so I can test it and deploy.

**Comment by genegr** [comment]
The new release with the requested enhacement is available

**Comment by chrroberts-pure** [comment]
Hi @jmg011 , In 1.0.3 ( #23 ) a new endpoint was added for this specific feature. 

Please query the new URI that was created in that release `/metrics/policies`  . The new URI is documented in README. 

Please let us know if you have further issues. 

v1.0.3.hotfix1 was released specifically for that bug with the error message. See issue #24 , and PR #25

**Comment by jmg011** [comment]
Thank you @chrroberts-pure 

@genegr  - I see purefb_nfs_export_rule policy metric but I do not see that policy name added to any of the filesystem/volume metric. 

So the idea is to have one metric with all the policy rules and one of the filesystem metric should have one more label with policy name. That way I can join both the metrics to get all the exports rules for a given volume/filesystem. 

Let me know if I missed looking at any filesystem metric. I looked for policy label and I could not find it on any filesystem metric.
