### ISSUE TITLE
RFE - Replication FS data

### ISSUE THREAD

**Issue by mboeckelmann** [PureStorage-OpenConnect/pure-fb-openmetrics-exporter#20]
Looking for information exposed via /file-system-replica-links to be included so we may track record of file systems replicated lag time and whether they are "protected" based on SLA.

**Comment by genegr** [comment]
Replica links metrics are included in the next minor release that is pending for approval. We should bump it out in a couple of days.

**Comment by mboeckelmann** [comment]
@genegr iss this in the current v1.03 pushed out or another release?

**Comment by sdodsley** [comment]
@mboeckelmann 1.0.3 is the latest release and should include this data

**Comment by mboeckelmann** [comment]
@sdodsley @genegr  thanks.  I see purefb_array_performance_replication, but this seems to be at array level.  any plan for individual replica links between fs or just at the array-wide level?

**Comment by sdodsley** [comment]
@mboeckelmann data from individual filesystems or buckets is not available. We would have to poll every link individually to get that data, and you can imagine that on a very large and heavily utilised FB that could take a considerable amount of time. This would cause the exporter to be very slow responding. This could lead to timeouts in the O11y application and loss of data points.

**Comment by fatghosts** [comment]
We are facing the issue that the replication link accumulate a huge amount of backlog, it has grow to more than 1xxTB and become a risk. We can use the following metrics in previous exporter to monitor the lag for each replication link to notice any backlog have accumulate, but we don't find any similar metric in this exporter.
purefb_bucket_replica_links_lag_msec
