### ISSUE TITLE
podman issue 

### ISSUE THREAD

**Issue by badharan** [PureStorage-OpenConnect/pure-fb-openmetrics-exporter#24]
Hello im trying to put run the container as podman 
podman run -p 9491:9491 --name pure-fb-om-exporter quay.io/purestorage/pure-fb-om-exporter
2023/05/10 16:50:32 Error in token file: unknown arguments --host 0.0.0.0

can please have a look

**Comment by badharan** [comment]
Any luck on this ?

**Comment by james-laing** [comment]
Hi @badharan,

Try changing `host: 0.0.0.0` to `address: 0.0.0.0`

**Comment by badharan** [comment]
Hi , 
Actually pullin dirctlry form registry ? is there is any command i need to encode with ?

**Comment by james-laing** [comment]
@badharan I have managed to recreate the error and I see what you are experiencing.

While we work on a fix for this are you able to to use the previous version?
`podman run -p 9491:9491 --name pure-fb-om-exporter quay.io/purestorage/pure-fb-om-exporter:v1.0.2`

**Comment by chrroberts-pure** [comment]
#25 was opened to correct this issue. 

This was an issue with the initialization of the binary within the docker image. I'll make sure it gets merged asap.

**Comment by badharan** [comment]
sure , Once done let us know . thanks

**Comment by sdodsley** [comment]
@badharan v1.0.3.hotfix1 released. You can get this image with 
`podman pull quay.io/purestorage/pure-fb-om-exporter:latest`
