### ISSUE TITLE
Volume Level Policy Metric from the Requested Enhancement.

### ISSUE THREAD

**Issue by jmg011** [PureStorage-OpenConnect/pure-fb-openmetrics-exporter#27]
Regarding Volume Level Policy Metric from the Requested Enhancement.

Original Enhancement Request: [(https://github.com/PureStorage-OpenConnect/pure-fb-openmetrics-exporter/issues/19)]

@genegr - I see purefb_nfs_export_rule policy metric but I do not see that policy name added to any of the filesystem/volume metric.

So the idea is to have one metric with all the policy rules and one of the filesystem metric should have one more label with policy name. That way I can join both the metrics to get all the exports rules for a given volume/filesystem.

Let me know if I missed looking at any filesystem metric. I looked for policy label and I could not find it on any filesystem metric.

Adding a screenshot from previous discussion on this thread.

![image](https://github.com/PureStorage-OpenConnect/pure-fb-openmetrics-exporter/assets/89614353/dff55d31-c49a-408d-bda7-c3f03ab2a92f)

**Comment by sdodsley** [comment]
There are no plans to include this metric as its implementation would adversely affect the rest of the exporter due to increased response times, potentially causing missing datapoints and making the returned data not real-time.
