### ISSUE TITLE
Target authorization token is missing

### ISSUE THREAD

**Issue by sridharatluri** [PureStorage-OpenConnect/pure-fb-openmetrics-exporter#38]
i have kept the token in yaml filen and getting Target authorization token is missing issue.

address: XXX.XXX.XXX.XXX
api_token: XXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by stratanic** [comment]
Same here,.... 
what is minimum version of the pure storage ? What is the requirements?

**Comment by Resha777** [comment]
same issue here 
my tokens.yaml file is this:
endpoint: x.x.x.x
api_token: XXXXXXX


when i do a curl with auth token i get result, but in the web i get Target authorization token is missing, please advice

**Comment by james-laing** [comment]
@sridharatluri @stratanic @Resha777 please can you share with us the full command you are using to execute the exporter?

It should look similar to this:
```
./pure-fb-openmetrics-exporter -t /directorytotokensfile/tokens.yaml -p 9491
```

It looks like several of you have been using `cURL` to test - note the name of the array in the `tokens.yaml` file MUST be the same as the one used in the query.
For example, if you wish to use address methods to query the endpoint you must add each method to the `tokens.yaml` file.
The following is an exaggerated example demonstrating being able to query the array metrics endpoint by
* alias
* FQDN
* IP address

```
$ cat /directorytotokensfile/tokens.yaml
arrayname1234:                              # MUST use this name/alias/ip in the query
  address: 'arrayname1234.fqdn.com'         # exporter will resolve the above name to use this address
  api_token: 'T-11111111-1111-1111-1111-111111111111'

arrayname1234.fqdn.com:
  address: 'arrayname1234.fqdn.com'
  api_token: 'T-11111111-1111-1111-1111-111111111111'

192.168.12.34
  address: 'arrayname1234.fqdn.com'         # of course you may use FQDN or IP address
  api_token: 'T-11111111-1111-1111-1111-111111111111'
```

### Example queries
**cURL**
```
curl -X GET 'http://openmetricsexporter.fqdn.com:9491/metrics/array?endpoint=arrayname1234'
```

**Browser**
If using the browser you must pass the array name endpoint for example:
http://openmetricsexporter.fqdn.com:9491/metrics/array?endpoint=arrayname1234

Let me know if you still need assistance.

**Comment by stratanic** [comment]
Very sorry..I realise i dont have an account to pure1.purestorage.com ...
I'm goin to call or email them to open an account...


**_I have to do the first step right ?_** 
https://support.purestorage.com/Pure1/Pure1_Manage/013_Pure1_Manage_-_REST_API/Pure1_REST_API_Postman_Collection_-_Setup_Guide

"Sign into Pure1 Manage (https://pure1.purestorage.com/) with an administrator account."

**Comment by stratanic** [comment]
i recreate the api token,


Error connecting to FlashBlade. Check your management endpoint and/or api token are correct.

![image](https://github.com/PureStorage-OpenConnect/pure-fb-openmetrics-exporter/assets/128167842/28cb1c8b-7a39-43f4-a7db-49e71ef1d4aa)

**Comment by james-laing** [comment]
@stratanic can you confirm the host `promethe1` can resolve the name of the FlashBlade endpoint?
Do you get the same result if you use the IP address or FQDN?

If name resolution is not the problem, please feel free to contact us directly at pure-observability@purestorage.com and we can arrange a call to discuss in real-time.

**Comment by stratanic** [comment]
I appreciate your assistance. I will now reach out to my support vendor for further assistance. 

Please note that I have two Pure Storage FlashArray (X20R3) systems not FlashBlade

**Comment by james-laing** [comment]
@stratanic Glad you got it up and running.

I will go ahead and close this issue.
