### ISSUE TITLE
Latency graphs in example Grafana dashboard are doubled

### ISSUE THREAD

**Issue by chrroberts-pure** [PureStorage-OpenConnect/pure-fb-openmetrics-exporter#49]
When using the base [Grafana dashboard ](https://github.com/PureStorage-OpenConnect/pure-fb-openmetrics-exporter/tree/main/extra/grafana) - when comparing to the Purity GUI, it seems that the values are doubled. Please see screenshot.

<img width="1834" alt="Screenshot 2024-02-20 at 11 22 11 AM" src="https://github.com/PureStorage-OpenConnect/pure-fb-openmetrics-exporter/assets/90332286/a5025ac7-9ad8-4426-9d21-10bcc72edef1">

**Comment by james-laing** [comment]
Thanks for raising this. I found the issue and have developed a fix for this to be issued soon.

**Comment by chrroberts-pure** [comment]
Closed by #52
