### ISSUE TITLE
scrape time issue with filesystem metrics 

### ISSUE THREAD

**Issue by jmg011** [PureStorage-OpenConnect/pure-fb-openmetrics-exporter#50]
Hi,

These two metrics do not return the data within the 2 minutes scrape interval. What is the expected scrape time for these metrics?

purefb_file_system_usage_groups_bytes
purefb_file_system_usage_users_bytes

Other metrics are scrapped fine on the same instances.

**Comment by james-laing** [comment]
Hi, thanks for your question.

This is a [known limitation](https://github.com/PureStorage-OpenConnect/pure-fb-openmetrics-exporter?tab=readme-ov-file#bugs-and-limitations) of way the query is handled by FlashBlade. Queries for `/metrics/clients` and `/metrics/usage` are expensive queries capturing a lot of metrics and depending on the size of the environment can take several minutes to complete. i.e. the more filesystems and clients, the longer the query will take.

It is advised to query `/metrics/array` as frequently as required for performance metrics. For `/metrics/clients` and `/metrics/usage` consider querying these much less frequent - once an hour is usually sufficient to gauge usage and client connection trends.

Thanks,
James.

**Comment by james-laing** [comment]
Glad to assist. I will close this issue.
