### ISSUE TITLE
Add metrics to display user & group level performance data for File System

### ISSUE THREAD

**Issue by skeerthivasan** [PureStorage-OpenConnect/pure-fb-openmetrics-exporter#6]
Expecting metric to show the data which will be shown in this UI page - https://fb.ip/analysis/performance/users - Performance by Users (NFS) and Performance by Groups (NFS). As far as I have checked we are collecting file system performance data but not to granular level of users and group.

Please plan to add the same.

**Comment by genegr** [comment]
The current FB internal code that extract those file system by users and groups performance data is too inefficient to let the related metrics reported by the exporter. Each query to the API allows to pass only a single file system name/id at time and it takes in the average 15 sec to return, which makes impractical implementing those metrics. We can certainly reconsider the opportunity if the collecting mechanism gets improved enough in future Purity FB releases.

**Comment by skeerthivasan** [comment]
Thanks for the update, I agree and It's understood that the expensive nature of the API call is blocking us to expose the metric.
