### ISSUE TITLE
Purefb Array Total Capacity

### ISSUE THREAD

**Issue by jmg011** [PureStorage-OpenConnect/pure-fb-openmetrics-exporter#67]
In 2021, I had initiated discussion with Pure team to get some answers on how to get the Array's total capacity from Purefb Metrics. 

The ask was to get this metric purefb_array_capacity_bytes to show the capacity of the array. In the meantime, I had created the static capacity timeseries metric for dashboards to fill the gap. 

I want to re-initiate the follow up on this so that we can get the Array capacity dynamically instead of statically. 

    def __init__(self, fb):
        self.fb = fb
        self.capacity = GaugeMetricFamily(**'purefb_array_capacity_bytes',**
                                       **'FlashBlade total capacity in bytes',**
                                       labels=[])

Can you please provide some information on this? 

Does this metric exist today? if not, is there a way to calculate this based off of current available metrics? If not, is there an API I can use to build this metric?

**Comment by chrroberts-pure** [comment]
Hi, 

We currently export this metric as 

`purefb_array_space_bytes{space="capacity",type="array"} 8.9937250028093e+13`

Please let me know if this fits your use case.
