### ISSUE TITLE
User I/O Performance per FileSystem

### ISSUE THREAD

**Issue by sdodsley** [PureStorage-OpenConnect/pure-fb-openmetrics-exporter#70]
Can we add this metric to the exporter.
Details of the API endpoint are: https://code.purestorage.com/swagger/redoc/fb2.13-api-reference.html#tag/File-Systems/paths/~1api~12.13~1file-systems~1policies-all/get
This will allow hot users to be identified.

**Comment by sdodsley** [comment]
Correction - this is the link: https://code.purestorage.com/swagger/redoc/fb2.13-api-reference.html#tag/File-Systems/paths/~1api~12.13~1file-systems~1users~1performance/get

**Comment by chrroberts-pure** [comment]
Hi, Thanks for the issue. 

When testing the API - it seemed that calling it took a very long time per file system. 


My initial testing with a pretty basic/empty FlashBlade - querying one file-system took >15 seconds. It is also required by the API to increment through the flie systems one-by-one. This will cause a scaling issue if it was implemented as is.

I'll be reaching out to our API teams to see if there was something I was doing incorrectly when calling the API, or why it may take this long to respond.  

Thanks!
